---
- hosts: kubernetes-master-nodes  

  tasks:
  - name: Copying Storageclass YAML File
    template: src=source_hci/storageclass_hci.yaml dest=/root
    
  - name: Creating basic storageclass 
    shell: kubectl create -f storageclass_hci.yaml
    args:
      chdir: /root

  - name: Copying Pvc YAML File
    template: src=source_hci/hci-basic-pvc.yaml dest=/root
    
  - name: Creating basic pvc
    shell: kubectl create -f hci-basic-pvc.yaml
    args:
      chdir: /root
      
  - name: Copying Pod YAML File
    template: src=source_hci/task-pv-pod.yaml dest=/root
    
  - name: Creating Pod with Mounting Vol 
    shell: kubectl create -f task-pv-pod.yaml
    args:
      chdir: /root    
